swagger: "2.0"

info:
  title: "Fanlens EEV API"
  version: "4.0.0"
  description: "API related to eev activity"

schemes:
  - https

basePath: /v4/eev

securityDefinitions:
  auth_token:
    type: apiKey
    name: Authorization
    in: header

security:
  - auth_token: []

produces:
  - application/json

paths:
  /login/{channel_id}/{user_id}:
    get:
      summary: login to chat service
      tags: [eev]
      produces:
      - text/html
      parameters:
      - name: channel_id
        in: path
        type: string
        required: true
      - name: user_id
        in: path
        type: string
        required: true
      responses:
        200:
          description: successfully logged in
        403:
          description: could not log in
definitions:
  Error:
    type: object
    properties:
      error:
        type: string
